In [2]:
import numpy as np

In [6]:
data = np.loadtxt("even_numbers.txt")
print(data)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]]


In [7]:
print(type(data))

<class 'numpy.ndarray'>


In [12]:
data = np.loadtxt("even_numbers.txt",dtype=int,skiprows=1,usecols=(1,3))
print(data)

[[14 18]
 [24 28]
 [34 38]
 [44 48]]


In [14]:
data = np.loadtxt("even_numbers.txt",dtype=int,usecols=(0))
print(data)

[ 2 12 22 32 42]


In [15]:
data = np.loadtxt("glass.csv",delimiter=',')
print(data)

[[  1.        1.52101  13.64    ...   0.        0.        1.     ]
 [  2.        1.51761  13.89    ...   0.        0.        1.     ]
 [  3.        1.51618  13.53    ...   0.        0.        1.     ]
 ...
 [212.        1.52065  14.36    ...   1.64      0.        7.     ]
 [213.        1.51651  14.38    ...   1.57      0.        7.     ]
 [214.        1.51711  14.23    ...   1.67      0.        7.     ]]


In [16]:
print(data.shape)

(214, 11)


In [18]:
print(data.dtype)

float64


In [19]:
print(data[:,1:])

[[ 1.52101 13.64     4.49    ...  0.       0.       1.     ]
 [ 1.51761 13.89     3.6     ...  0.       0.       1.     ]
 [ 1.51618 13.53     3.55    ...  0.       0.       1.     ]
 ...
 [ 1.52065 14.36     0.      ...  1.64     0.       7.     ]
 [ 1.51651 14.38     0.      ...  1.57     0.       7.     ]
 [ 1.51711 14.23     0.      ...  1.67     0.       7.     ]]


In [20]:
data = np.genfromtxt('odd_numbers.txt',invalid_raise=False)

ValueError: Some errors were detected !
    Line #5 (got 4 columns instead of 5)

In [21]:
print(data)

[[  1.        1.52101  13.64    ...   0.        0.        1.     ]
 [  2.        1.51761  13.89    ...   0.        0.        1.     ]
 [  3.        1.51618  13.53    ...   0.        0.        1.     ]
 ...
 [212.        1.52065  14.36    ...   1.64      0.        7.     ]
 [213.        1.51651  14.38    ...   1.57      0.        7.     ]
 [214.        1.51711  14.23    ...   1.67      0.        7.     ]]


In [23]:
data = np.genfromtxt('odd_numbers.csv',delimiter = ',')

In [24]:
print(data)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [43. 45. 47. 49. nan]]


In [25]:
data = np.genfromtxt('odd_numbers.csv',delimiter = ',',filling_values=0)
print(data)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [43. 45. 47. 49.  0.]]


In [29]:
data = np.genfromtxt("highway.csv",delimiter = ',',dtype = np.str)
data[data == "?"]='unknown'
print(data)

[['E1' 'M' '3' ... 'SHORT' 'S' 'WOOD']
 ['E2' 'A' '25' ... 'SHORT' 'S' 'WOOD']
 ['E3' 'A' '39' ... 'unknown' 'S' 'WOOD']
 ...
 ['E90' 'M' '7' ... 'LONG' 'F' 'ARCH']
 ['E100' 'O' '43' ... 'unknown' 'F' 'unknown']
 ['E109' 'A' '28' ... 'unknown' 'F' 'unknown']]


C:\Users\adity\AppData\Local\Temp/ipykernel_10796/3204588460.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = np.genfromtxt("highway.csv",delimiter = ',',dtype = np.str)


In [31]:
dat = data[:,1]
print(dat)

['M' 'A' 'A' 'A' 'M' 'A' 'A' 'M' 'A' 'A' 'A' 'M' 'A' 'A' 'A' 'M' 'A' 'A'
 'A' 'M' 'M' 'A' 'O' 'M' 'A' 'M' 'A' 'A' 'M' 'A' 'M' 'O' 'M' 'O' 'A' 'M'
 'M' 'A' 'A' 'M' 'M' 'M' 'O' 'M' 'A' 'M' 'M' 'A' 'A' 'M' 'A' 'M' 'A' 'M'
 'M' 'M' 'A' 'M' 'Y' 'M' 'A' 'O' 'O' 'A' 'M' 'O' 'A' 'A' 'A' 'A' 'A' 'A'
 'A' 'A' 'O' 'A' 'M' 'M' 'A' 'M' 'A' 'M' 'O' 'O' 'M' 'M' 'A' 'A' 'A' 'A'
 'O' 'Y' 'Y' 'M' 'M' 'M' 'M' 'A' 'O' 'O' 'M' 'A' 'M' 'A' 'O' 'M' 'O' 'A']


In [33]:
M=0
for i in dat:
    if (i=='M'):
        M+=1
print(M)

41


In [34]:
A=0
for i in dat:
    if(i=='A'):
        A+=1
print(A)

49


In [35]:
O=0
for i in dat:
    if(i=='O'):
        O+=1
print(O)

15
